### ISSUE TITLE
Is there a way to retweet all the time there is a tweet with the hashtag? 

### ISSUE THREAD

**Issue by venturaEffect** [mayeedwin/twitterbot#5]
I'm just curious about how to tweak the code to make it work in different scenarios. I'm especially interested that it posts each time there is a new post with the hashtag. Not just one each hour.

Love twitterbot and appreciate your time!

**Comment by venturaEffect** [comment]
I've commented on bot.js the line 38
`// setInterval(retweetLatest, 1000 * 60 * 30);
`

Hope that does the trick!

Any guidance will be appreciated

**Comment by mayeedwin** [comment]
But still you can publish the bot on Firebase functions for example, to have everything done for you. In the moment, stuff is manual.
